// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'container': string;
  'heading': string;
  'image': string;
  'left': string;
  'right': string;
}
declare var cssExports: CssExports;
export = cssExports;
