// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'body': string;
  'common': string;
  'heading': string;
  'heading3': string;
}
declare var cssExports: CssExports;
export = cssExports;
